version: '3'

services:
  ai-models-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      # Mount static folders for persistent storage
      - ./static/uploads:/app/static/uploads
      - ./static/results:/app/static/results
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - FLASK_DEBUG=False
      # Add your other environment variables here
      # - GEMINI_API_KEY=your_api_key
    restart: unless-stopped
